/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './github-profile.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './github-profile.component';
import * as i3 from '@angular/router';
const styles_GithubProfileComponent:any[] = [i0.styles];
export const RenderType_GithubProfileComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_GithubProfileComponent,data:{}});
export function View_GithubProfileComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  github-profile works!\n'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n'])),(_l()(),i1.ɵeld(3,0,(null as any),(null as any),1,'button',
      [['class','btn btn-primary']],(null as any),[[(null as any),'click']],(_v,en,
          $event) => {
        var ad:boolean = true;
        var _co:i2.GithubProfileComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.submit()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['Next']))],
      (null as any),(null as any));
}
export function View_GithubProfileComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-github-profile',
      ([] as any[]),(null as any),(null as any),(null as any),View_GithubProfileComponent_0,
      RenderType_GithubProfileComponent)),i1.ɵdid(1,114688,(null as any),0,i2.GithubProfileComponent,
      [i3.ActivatedRoute,i3.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const GithubProfileComponentNgFactory:i1.ComponentFactory<i2.GithubProfileComponent> = i1.ɵccf('app-github-profile',
    i2.GithubProfileComponent,View_GithubProfileComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2dpdGh1Yi1wcm9maWxlL2dpdGh1Yi1wcm9maWxlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvZ2l0aHViLXByb2ZpbGUvZ2l0aHViLXByb2ZpbGUuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2dpdGh1Yi1wcm9maWxlL2dpdGh1Yi1wcm9maWxlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2dpdGh1Yi1wcm9maWxlL2dpdGh1Yi1wcm9maWxlLmNvbXBvbmVudC50cy5HaXRodWJQcm9maWxlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIGdpdGh1Yi1wcm9maWxlIHdvcmtzIVxuPC9wPlxuPGJ1dHRvbiAoY2xpY2spPVwic3VibWl0KClcIiBjbGFzcz1cImJ0biBidG4tcHJpbWFyeVwiPk5leHQ8L2J1dHRvbj4iLCI8YXBwLWdpdGh1Yi1wcm9maWxlPjwvYXBwLWdpdGh1Yi1wcm9maWxlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLG9EQUVDO01BQUEsdUJBQ0o7TUFBQTtnQkFBQTtRQUFBO1FBQUE7UUFBUTtVQUFBO1VBQUE7UUFBQTtRQUFSO01BQUEsZ0NBQW1EOzs7O29CQ0huRDtNQUFBO3VDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
