/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './zippy.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './zippy.component';
import * as i3 from '@angular/common';
const styles_ZippyComponent:any[] = [i0.styles];
export const RenderType_ZippyComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ZippyComponent,data:{}});
function View_ZippyComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),3,'div',[['class',
      'zippy-body']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n    '])),i1.ɵncd((null as any),0),(_l()(),
          i1.ɵted(-1,(null as any),['\n  ']))],(null as any),(null as any));
}
export function View_ZippyComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),11,'div',[['class','zippy']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['\n  '])),(_l()(),i1.ɵeld(3,0,(null as any),(null as any),5,'div',[['class',
      'zippy-heading']],[[2,'expanded',(null as any)]],[[(null as any),'click']],(_v,
      en,$event) => {
    var ad:boolean = true;
    var _co:i2.ZippyComponent = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.toggle()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i1.ɵted(4,(null as any),['\n    ','\n    '])),
      (_l()(),i1.ɵeld(5,0,(null as any),(null as any),2,'span',[['class','glyphicon']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(6,278528,(null as any),0,i3.NgClass,[i1.IterableDiffers,i1.KeyValueDiffers,
          i1.ElementRef,i1.Renderer],{klass:[0,'klass'],ngClass:[1,'ngClass']},(null as any)),
      i1.ɵpod(7,{'glyphicon-chevron-up':0,'glyphicon-chevron-down':1}),(_l()(),i1.ɵted(-1,
          (null as any),['\n  '])),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),
          i1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_ZippyComponent_1)),
      i1.ɵdid(11,16384,(null as any),0,i3.NgIf,[i1.ViewContainerRef,i1.TemplateRef],
          {ngIf:[0,'ngIf']},(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n']))],
      (_ck,_v) => {
        var _co:i2.ZippyComponent = _v.component;
        const currVal_2:any = 'glyphicon';
        const currVal_3:any = _ck(_v,7,0,_co.isExpanded,!_co.isExpanded);
        _ck(_v,6,0,currVal_2,currVal_3);
        const currVal_4:any = _co.isExpanded;
        _ck(_v,11,0,currVal_4);
      },(_ck,_v) => {
        var _co:i2.ZippyComponent = _v.component;
        const currVal_0:any = _co.isExpanded;
        _ck(_v,3,0,currVal_0);
        const currVal_1:any = _co.title;
        _ck(_v,4,0,currVal_1);
      });
}
export function View_ZippyComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'zippy',([] as any[]),
      (null as any),(null as any),(null as any),View_ZippyComponent_0,RenderType_ZippyComponent)),
      i1.ɵdid(1,49152,(null as any),0,i2.ZippyComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ZippyComponentNgFactory:i1.ComponentFactory<i2.ZippyComponent> = i1.ɵccf('zippy',
    i2.ZippyComponent,View_ZippyComponent_Host_0,{title:'title'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3ppcHB5L3ppcHB5LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvemlwcHkvemlwcHkuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3ppcHB5L3ppcHB5LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3ppcHB5L3ppcHB5LmNvbXBvbmVudC50cy5aaXBweUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPGRpdiBjbGFzcz1cInppcHB5XCI+XG4gIDxkaXYgXG4gICAgY2xhc3M9XCJ6aXBweS1oZWFkaW5nXCJcbiAgICBbY2xhc3MuZXhwYW5kZWRdPVwiaXNFeHBhbmRlZFwiXG4gICAgKGNsaWNrKT1cInRvZ2dsZSgpXCJcbiAgICA+XG4gICAge3sgdGl0bGUgfX1cbiAgICA8c3BhbiBjbGFzcz1cImdseXBoaWNvblwiXG4gICAgICBbbmdDbGFzc109XCJ7XG4gICAgICAgICdnbHlwaGljb24tY2hldnJvbi11cCc6IGlzRXhwYW5kZWQsXG4gICAgICAgICdnbHlwaGljb24tY2hldnJvbi1kb3duJzogIWlzRXhwYW5kZWRcbiAgICAgIH1cIlxuICAgID48L3NwYW4+XG4gIDwvZGl2PlxuICA8ZGl2ICpuZ0lmPVwiaXNFeHBhbmRlZFwiIGNsYXNzPVwiemlwcHktYm9keVwiPlxuICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgPC9kaXY+XG48L2Rpdj4iLCI8emlwcHk+PC96aXBweT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ2VFO01BQUE7TUFBMkMscURBQ3pDLGtCQUF5QjtpQkFBQTs7O29CQWhCN0IsMENBQ0E7TUFBQTtNQUFBLDRDQUFtQjtNQUFBLFdBQ2pCO01BQUE7ZUFBQTtJQUFBO0lBQUE7SUFHRTtNQUFBO01BQUE7SUFBQTtJQUhGO0VBQUEsZ0NBSUc7TUFFRDtVQUFBO2FBQUE7bUNBQUE7YUFDRSwwREFJTTtVQUFBLHlCQUNKLDRDQUNOO2lCQUFBO2FBQUE7VUFBQSxpQ0FFTTs7O1FBVEU7UUFDSjtRQURGLFdBQU0sVUFDSixTQURGO1FBT0c7UUFBTCxZQUFLLFNBQUw7OztRQVhFO1FBRkYsV0FFRSxTQUZGO1FBSUc7UUFBQTs7OztvQkNOTDtNQUFBO2FBQUE7VUFBQTs7OyJ9
