/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.zippy[_ngcontent-%COMP%] { \n    border: 1px solid #ccc;\n    border-radius: 2px;\n}\n\n.zippy-heading[_ngcontent-%COMP%] { \n    font-weight: bold;\n    padding: 20px;\n    cursor: pointer;\n}\n\n.zippy-body[_ngcontent-%COMP%] { \n    padding: 20px;\n}\n\n.expanded[_ngcontent-%COMP%] { \n    background: #f0f0f0;\n}\n\n.glyphicon[_ngcontent-%COMP%] { \n    float: right;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3ppcHB5L3ppcHB5LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3ppcHB5L3ppcHB5LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
