/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './summary.pipe';
import * as i2 from './courses.component';
const styles_CoursesComponent:any[] = ([] as any[]);
export const RenderType_CoursesComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_CoursesComponent,data:{}});
export function View_CoursesComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵpid(0,i1.SummaryPipe,([] as any[])),(_l()(),i0.ɵted(1,(null as any),
      ['\n        ','\n    '])),i0.ɵppd(2,2)],(null as any),(_ck,_v) => {
    var _co:i2.CoursesComponent = _v.component;
    const currVal_0:any = i0.ɵunv(_v,1,0,_ck(_v,2,0,i0.ɵnov(_v,0),_co.text,10));
    _ck(_v,1,0,currVal_0);
  });
}
export function View_CoursesComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'courses',([] as any[]),
      (null as any),(null as any),(null as any),View_CoursesComponent_0,RenderType_CoursesComponent)),
      i0.ɵdid(1,49152,(null as any),0,i2.CoursesComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const CoursesComponentNgFactory:i0.ComponentFactory<i2.CoursesComponent> = i0.ɵccf('courses',
    i2.CoursesComponent,View_CoursesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2NvdXJzZXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0FuZ3VsYXIgMi9Nb3NoLUFuZ3VsYXItMi1tYXN0ZXIvc3JjL2FwcC9jb3Vyc2VzLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0FuZ3VsYXIgMi9Nb3NoLUFuZ3VsYXItMi1tYXN0ZXIvc3JjL2FwcC9jb3Vyc2VzLmNvbXBvbmVudC50cy5Db3Vyc2VzQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvY291cnNlcy5jb21wb25lbnQudHMuQ291cnNlc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICB7eyB0ZXh0IHwgc3VtbWFyeToxMCB9fVxuICAgICIsIjxjb3Vyc2VzPjwvY291cnNlcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7NERDQUE7TUFBQTs7SUFBQTtJQUFBOzs7O29CQ0FBO01BQUE7YUFBQTtVQUFBOzs7In0=
