/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './like.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './like.component';
const styles_LikeComponent:any[] = [i0.styles];
export const RenderType_LikeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_LikeComponent,data:{}});
export function View_LikeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),1,'span',[['class','glyphicon glyphicon-heart']],
      [[2,'highlighted',(null as any)]],[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i2.LikeComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onClick()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),
      i1.ɵted(-1,(null as any),['\n\n'])),(_l()(),i1.ɵeld(4,0,(null as any),(null as any),
      1,'span',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(5,(null as any),['','']))],(null as any),(_ck,
      _v) => {
    var _co:i2.LikeComponent = _v.component;
    const currVal_0:any = _co.isActive;
    _ck(_v,1,0,currVal_0);
    const currVal_1:any = _co.likesCount;
    _ck(_v,5,0,currVal_1);
  });
}
export function View_LikeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'like',([] as any[]),
      (null as any),(null as any),(null as any),View_LikeComponent_0,RenderType_LikeComponent)),
      i1.ɵdid(1,49152,(null as any),0,i2.LikeComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const LikeComponentNgFactory:i1.ComponentFactory<i2.LikeComponent> = i1.ɵccf('like',
    i2.LikeComponent,View_LikeComponent_Host_0,{likesCount:'likesCount',isActive:'isActive'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2xpa2UvbGlrZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2xpa2UvbGlrZS5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvbGlrZS9saWtlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2xpa2UvbGlrZS5jb21wb25lbnQudHMuTGlrZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPHNwYW4gXG4gIGNsYXNzPVwiZ2x5cGhpY29uIGdseXBoaWNvbi1oZWFydFwiXG4gIFtjbGFzcy5oaWdobGlnaHRlZF09XCJpc0FjdGl2ZVwiXG4gIChjbGljayk9XCJvbkNsaWNrKClcIj5cbjwvc3Bhbj5cblxuPHNwYW4+e3sgbGlrZXNDb3VudCB9fTwvc3Bhbj4iLCI8bGlrZT48L2xpa2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDBDQUNBO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFHRTtVQUFBO1VBQUE7UUFBQTtRQUhGO01BQUEsZ0NBR3NCLDBDQUNmO2FBQUEsNkJBRVA7TUFBQTtNQUFBLGdCQUFNOzs7SUFKSjtJQUZGLFdBRUUsU0FGRjtJQU1NO0lBQUE7Ozs7b0JDUE47TUFBQTthQUFBO1VBQUE7Ozs7In0=
