/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './archive.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './archive.component';
import * as i3 from '@angular/router';
const styles_ArchiveComponent:any[] = [i0.styles];
export const RenderType_ArchiveComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ArchiveComponent,data:{}});
export function View_ArchiveComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(1,(null as any),['\n  Archive for ',' / ','\n'])),(_l()(),i1.ɵted(-1,
      (null as any),['\n\n'])),(_l()(),i1.ɵeld(3,0,(null as any),(null as any),1,'button',
      ([] as any[]),(null as any),[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i2.ArchiveComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.submit()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['View All']))],
      (null as any),(_ck,_v) => {
        var _co:i2.ArchiveComponent = _v.component;
        const currVal_0:any = _co.year;
        const currVal_1:any = _co.month;
        _ck(_v,1,0,currVal_0,currVal_1);
      });
}
export function View_ArchiveComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-archive',
      ([] as any[]),(null as any),(null as any),(null as any),View_ArchiveComponent_0,
      RenderType_ArchiveComponent)),i1.ɵdid(1,114688,(null as any),0,i2.ArchiveComponent,
      [i3.ActivatedRoute,i3.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ArchiveComponentNgFactory:i1.ComponentFactory<i2.ArchiveComponent> = i1.ɵccf('app-archive',
    i2.ArchiveComponent,View_ArchiveComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2FyY2hpdmUvYXJjaGl2ZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2FyY2hpdmUvYXJjaGl2ZS5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvYXJjaGl2ZS9hcmNoaXZlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2FyY2hpdmUvYXJjaGl2ZS5jb21wb25lbnQudHMuQXJjaGl2ZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5cbiAgQXJjaGl2ZSBmb3Ige3t5ZWFyfX0gLyB7e21vbnRofX1cbjwvaDE+XG5cbjxidXR0b24gKGNsaWNrKT1cInN1Ym1pdCgpXCI+VmlldyBBbGw8L2J1dHRvbj4iLCI8YXBwLWFyY2hpdmU+PC9hcHAtYXJjaGl2ZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUk7YUFBQSxtREFFQztNQUFBLHlCQUVMO01BQUE7UUFBQTtRQUFBO1FBQVE7VUFBQTtVQUFBO1FBQUE7UUFBUjtNQUFBLGdDQUEyQjs7O1FBSnZCO1FBQUE7UUFBQTs7OztvQkNBSjtNQUFBO2lDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
