/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './posts.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './posts.component';
import * as i3 from '@angular/common';
import * as i4 from '../services/post.service';
const styles_PostsComponent:any[] = [i0.styles];
export const RenderType_PostsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PostsComponent,data:{}});
function View_PostsComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),4,'li',[['class',
      'list-group-item']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵeld(2,
      0,(null as any),(null as any),1,'button',[['class','btn btn-default btn-sm']],
      (null as any),[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.deletePost(_v.context.$implicit)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['Delete'])),
      (_l()(),i1.ɵted(4,(null as any),['\n    ','\n  ']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit.title;
    _ck(_v,4,0,currVal_0);
  });
}
export function View_PostsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,[['title',1]],(null as any),0,'input',[['class',
      'form-control'],['type','text']],(null as any),[[(null as any),'keyup.enter']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:i2.PostsComponent = _v.component;
        if (('keyup.enter' === en)) {
          const pd_0:any = ((<any>_co.createPost(i1.ɵnov(_v,0))) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),
      i1.ɵeld(2,0,(null as any),(null as any),4,'ul',[['class','list-group']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
      (null as any),['\n  '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),
      1,(null as any),View_PostsComponent_1)),i1.ɵdid(5,802816,(null as any),0,i3.NgForOf,
      [i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,'ngForOf']},
      (null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    var _co:i2.PostsComponent = _v.component;
    const currVal_0:any = _co.posts;
    _ck(_v,5,0,currVal_0);
  },(null as any));
}
export function View_PostsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-posts',
      ([] as any[]),(null as any),(null as any),(null as any),View_PostsComponent_0,
      RenderType_PostsComponent)),i1.ɵdid(1,114688,(null as any),0,i2.PostsComponent,
      [i4.PostService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PostsComponentNgFactory:i1.ComponentFactory<i2.PostsComponent> = i1.ɵccf('app-posts',
    i2.PostsComponent,View_PostsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3Bvc3RzL3Bvc3RzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvcG9zdHMvcG9zdHMuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3Bvc3RzL3Bvc3RzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3Bvc3RzL3Bvc3RzLmNvbXBvbmVudC50cy5Qb3N0c0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxpbnB1dCBcbiAgKGtleXVwLmVudGVyKT1cImNyZWF0ZVBvc3QodGl0bGUpXCIgI3RpdGxlXG4gIHR5cGU9XCJ0ZXh0XCIgY2xhc3M9XCJmb3JtLWNvbnRyb2xcIj5cbjx1bCBjbGFzcz1cImxpc3QtZ3JvdXBcIj5cbiAgPGxpIFxuICAgICpuZ0Zvcj1cImxldCBwb3N0IG9mIHBvc3RzXCJcbiAgICBjbGFzcz1cImxpc3QtZ3JvdXAtaXRlbVwiPlxuICAgIDxidXR0b24gXG4gICAgICAoY2xpY2spPVwiZGVsZXRlUG9zdChwb3N0KVwiXG4gICAgICBjbGFzcz1cImJ0biBidG4tZGVmYXVsdCBidG4tc21cIj5EZWxldGU8L2J1dHRvbj5cbiAgICB7eyBwb3N0LnRpdGxlIH19XG4gIDwvbGk+XG48L3VsPiIsIjxhcHAtcG9zdHM+PC9hcHAtcG9zdHM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDSUU7TUFBQTtNQUFBLGdCQUUwQiw4Q0FDeEI7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUNFO1VBQUE7VUFBQTtRQUFBO1FBREY7TUFBQSxnQ0FFaUM7TUFBZTtJQUFBO0lBQUE7Ozs7b0JBVHBEO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFDRTtVQUFBO1VBQUE7UUFBQTtRQURGO01BQUEsZ0NBRW1DLDBDQUNuQzthQUFBO1VBQUEsMERBQXVCO01BQUEseUJBQ3JCO01BQUEsK0NBQUE7TUFBQTtNQUFBLGVBT0s7O0lBTkg7SUFERixXQUNFLFNBREY7Ozs7b0JDSkY7TUFBQTsrQkFBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
