/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './authors.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './authors.component';
import * as i4 from '../authors.service';
const styles_AuthorsComponent:any[] = [i0.styles];
export const RenderType_AuthorsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AuthorsComponent,data:{}});
function View_AuthorsComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(1,(null as any),['\n    ','\n  ']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_AuthorsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'h2',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(1,(null as any),['',' Authors'])),(_l()(),i1.ɵted(-1,(null as any),['\n'])),
      (_l()(),i1.ɵeld(3,0,(null as any),(null as any),4,'ul',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
          (null as any),['\n  '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),
          1,(null as any),View_AuthorsComponent_1)),i1.ɵdid(6,802816,(null as any),
          0,i2.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,
              'ngForOf']},(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n']))],
      (_ck,_v) => {
        var _co:i3.AuthorsComponent = _v.component;
        const currVal_1:any = _co.authors;
        _ck(_v,6,0,currVal_1);
      },(_ck,_v) => {
        var _co:i3.AuthorsComponent = _v.component;
        const currVal_0:any = _co.authors.length;
        _ck(_v,1,0,currVal_0);
      });
}
export function View_AuthorsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'authors',([] as any[]),
      (null as any),(null as any),(null as any),View_AuthorsComponent_0,RenderType_AuthorsComponent)),
      i1.ɵdid(1,114688,(null as any),0,i3.AuthorsComponent,[i4.AuthorsService],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AuthorsComponentNgFactory:i1.ComponentFactory<i3.AuthorsComponent> = i1.ɵccf('authors',
    i3.AuthorsComponent,View_AuthorsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2F1dGhvcnMvYXV0aG9ycy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2F1dGhvcnMvYXV0aG9ycy5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvYXV0aG9ycy9hdXRob3JzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2F1dGhvcnMvYXV0aG9ycy5jb21wb25lbnQudHMuQXV0aG9yc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMj57eyBhdXRob3JzLmxlbmd0aCB9fSBBdXRob3JzPC9oMj5cbjx1bD5cbiAgPGxpICpuZ0Zvcj1cImxldCBhdXRob3Igb2YgYXV0aG9yc1wiPlxuICAgIHt7IGF1dGhvciB9fVxuICA8L2xpPlxuPC91bD4iLCI8YXV0aG9ycz48L2F1dGhvcnM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDRUU7TUFBQSx3RUFBbUM7YUFBQTtJQUFBO0lBQUE7Ozs7b0JBRnJDO01BQUEsd0VBQUk7YUFBQSxtQ0FBaUM7TUFDckM7VUFBQSwwREFBSTtVQUFBLHlCQUNGO1VBQUEsaURBQUE7VUFBQTtjQUFBLDJCQUVLOzs7UUFGRDtRQUFKLFdBQUksU0FBSjs7O1FBRkU7UUFBQTs7OztvQkNBSjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
