/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.avatar[_ngcontent-%COMP%] { \n    width: 80px;\n    height: 80px;\n    border-radius: 100%;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2dpdGh1Yi1mb2xsb3dlcnMvZ2l0aHViLWZvbGxvd2Vycy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0FuZ3VsYXIgMi9Nb3NoLUFuZ3VsYXItMi1tYXN0ZXIvc3JjL2FwcC9naXRodWItZm9sbG93ZXJzL2dpdGh1Yi1mb2xsb3dlcnMuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
