/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './favorite.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './favorite.component';
import * as i3 from '@angular/common';
const styles_FavoriteComponent:any[] = [i0.styles];
export const RenderType_FavoriteComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_FavoriteComponent,data:{}});
export function View_FavoriteComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),2,'span',[['class',
      'glyphicon']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:i2.FavoriteComponent = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.onClick()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),i1.ɵdid(1,278528,(null as any),0,i3.NgClass,[i1.IterableDiffers,
      i1.KeyValueDiffers,i1.ElementRef,i1.Renderer],{klass:[0,'klass'],ngClass:[1,
      'ngClass']},(null as any)),i1.ɵpod(2,{'glyphicon-star':0,'glyphicon-star-empty':1})],
      (_ck,_v) => {
        var _co:i2.FavoriteComponent = _v.component;
        const currVal_0:any = 'glyphicon';
        const currVal_1:any = _ck(_v,2,0,_co.isSelected,!_co.isSelected);
        _ck(_v,1,0,currVal_0,currVal_1);
      },(null as any));
}
export function View_FavoriteComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'favorite',([] as any[]),
      (null as any),(null as any),(null as any),View_FavoriteComponent_0,RenderType_FavoriteComponent)),
      i1.ɵdid(1,49152,(null as any),0,i2.FavoriteComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const FavoriteComponentNgFactory:i1.ComponentFactory<i2.FavoriteComponent> = i1.ɵccf('favorite',
    i2.FavoriteComponent,View_FavoriteComponent_Host_0,{isSelected:'isFavorite'},{click:'change'},
    ([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2Zhdm9yaXRlL2Zhdm9yaXRlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvZmF2b3JpdGUvZmF2b3JpdGUuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2Zhdm9yaXRlL2Zhdm9yaXRlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL2Zhdm9yaXRlL2Zhdm9yaXRlLmNvbXBvbmVudC50cy5GYXZvcml0ZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxzcGFuIFxuICBjbGFzcz1cImdseXBoaWNvblwiXG4gIFtuZ0NsYXNzXT1cIntcbiAgICAnZ2x5cGhpY29uLXN0YXInOiBpc1NlbGVjdGVkLFxuICAgICdnbHlwaGljb24tc3Rhci1lbXB0eSc6ICFpc1NlbGVjdGVkXG4gIH1cIlxuICAoY2xpY2spPVwib25DbGljaygpXCJcbiAgPjwvc3Bhbj4iLCI8ZmF2b3JpdGU+PC9mYXZvcml0ZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7SUFBQTtJQUFBO0lBTUU7TUFBQTtNQUFBO0lBQUE7SUFORjtFQUFBLHVDQUFBO2tEQUFBO01BQUEsa0NBRUU7OztRQURBO1FBQ0E7UUFGRixXQUNFLFVBQ0EsU0FGRjs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTs7OzsifQ==
