/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './panel.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './panel.component';
const styles_PanelComponent:any[] = [i0.styles];
export const RenderType_PanelComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PanelComponent,data:{}});
export function View_PanelComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),11,'div',[['class','panel panel-default']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
      (null as any),['\n  '])),(_l()(),i1.ɵeld(3,0,(null as any),(null as any),3,'div',
      [['class','panel-heading']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n    '])),i1.ɵncd((null as any),
      0),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n  '])),(_l()(),i1.ɵeld(8,0,(null as any),(null as any),3,'div',[['class',
      'panel-body']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n    '])),i1.ɵncd((null as any),1),(_l()(),
          i1.ɵted(-1,(null as any),['    \n  '])),(_l()(),i1.ɵted(-1,(null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_PanelComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'bootstrap-panel',
      ([] as any[]),(null as any),(null as any),(null as any),View_PanelComponent_0,
      RenderType_PanelComponent)),i1.ɵdid(1,49152,(null as any),0,i2.PanelComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const PanelComponentNgFactory:i1.ComponentFactory<i2.PanelComponent> = i1.ɵccf('bootstrap-panel',
    i2.PanelComponent,View_PanelComponent_Host_0,{},{},['.heading','.body']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3BhbmVsL3BhbmVsLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Bbmd1bGFyIDIvTW9zaC1Bbmd1bGFyLTItbWFzdGVyL3NyYy9hcHAvcGFuZWwvcGFuZWwuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3BhbmVsL3BhbmVsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQW5ndWxhciAyL01vc2gtQW5ndWxhci0yLW1hc3Rlci9zcmMvYXBwL3BhbmVsL3BhbmVsLmNvbXBvbmVudC50cy5QYW5lbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPGRpdiBjbGFzcz1cInBhbmVsIHBhbmVsLWRlZmF1bHRcIj5cbiAgPGRpdiBjbGFzcz1cInBhbmVsLWhlYWRpbmdcIj5cbiAgICA8bmctY29udGVudCBzZWxlY3Q9XCIuaGVhZGluZ1wiPjwvbmctY29udGVudD5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJwYW5lbC1ib2R5XCI+XG4gICAgPG5nLWNvbnRlbnQgc2VsZWN0PVwiLmJvZHlcIj48L25nLWNvbnRlbnQ+ICAgIFxuICA8L2Rpdj5cbjwvZGl2PiIsIjxib290c3RyYXAtcGFuZWw+PC9ib290c3RyYXAtcGFuZWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDBDQUNBO01BQUE7TUFBQSwwREFBaUM7TUFBQSx5QkFDL0I7TUFBQTtNQUFBLGdCQUEyQixxREFDekI7TUFBQSxHQUEyQyw0Q0FDdkM7TUFBQSxXQUNOO01BQUE7TUFBd0IscURBQ3RCLGtCQUF3QztpQkFBQSxpQ0FDcEM7VUFBQTs7O29CQ1BSO01BQUE7K0JBQUEsVUFBQTtNQUFBOzs7In0=
